### PR TITLE
fixing typo, no functional change

### PR DESCRIPTION
**Pull request by carlsverre**
Just something I noticed.  Awesome example of a go generics project.  Love it!

### CODE REVIEW

**Comment by dahankzter** [comment]
Thanks for noticing this. Could you perhaps also regenerate the resulting code so the name change takes effect?

**Comment by mmatczuk** [comment]
Not necessary, just rename `b8set/b16set.go` accordingly.

**Comment by dahankzter** [comment]
Oh yeah, building Bazel for this change is harsh.

**Comment by carlsverre** [comment]
Done :)

**Comment by mmatczuk** [comment]
Thanks!

**Pull request merged**
